# Generated by Django 4.0 on 2023-10-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendEMAJ', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='assistido',
        ),
    ]
