# Generated by Django 4.0 on 2023-10-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendEMAJ', '0002_rename_nome_pecas_name_rename_nome_usuario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistido',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='rg',
            field=models.IntegerField(unique=True, verbose_name=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
