# Generated by Django 4.0 on 2023-10-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendEMAJ', '0002_rename_user_assistido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assistido',
        ),
    ]
