# Generated by Django 4.0 on 2023-11-08 18:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendEMAJ', '0003_alter_assistido_cpf_alter_assistido_rg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.IntegerField(unique=True, verbose_name=20)),
                ('dataNasc', models.DateField(max_length=8)),
                ('estadoCivil', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='assistido',
            old_name='representante',
            new_name='estadoCivil',
        ),
        migrations.AlterField(
            model_name='assistido',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='telefone1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='telefone2',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='assistido',
            name='representado',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='backendEMAJ.representado'),
        ),
    ]
