# Generated by Django 4.0 on 2023-11-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendEMAJ', '0004_representado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistido',
            name='id_uuid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='representado',
            name='id_uuid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_uuid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
