# Generated by Django 4.0 on 2023-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendEMAJ', '0005_assistido_id_uuid_representado_id_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistido',
            name='id_uuid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='representado',
            name='id_uuid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_uuid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
